name: modgen --check

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: build
        run: dotnet build -f net9.0

      - name: modgen
        run: dotnet run --project TopModel.Generator/TopModel.Generator.csproj -f net9.0 -- -c

      - name: tmdgen
        run: dotnet run --project TopModel.ModelGenerator/TopModel.ModelGenerator.csproj -f net9.0 -- -f samples/generators/open-api/tmdgen.config -c

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn test -f ./samples/generators/jpa/